// Generated by asm2go -file src/addition.s -gofile addition/addition_amd64.go -out addition/addition_amd64.s DO NOT EDIT
#include "textflag.h"

// func Add2(x, y int) int
TEXT ·Add2(SB), NOSPLIT, $0-8
    BYTE $0x55;    // push      %rbp   
    WORD $0x8948;  BYTE $0xe5;  // mov %rsp       %rbp       
    WORD $0x7d89;  BYTE $0xfc;  // mov %edi       -0x4(%rbp) 
    WORD $0x7589;  BYTE $0xf8;  // mov %esi       -0x8(%rbp) 
    WORD $0x558b;  BYTE $0xfc;  // mov -0x4(%rbp) %edx       
    WORD $0x458b;  BYTE $0xf8;  // mov -0x8(%rbp) %eax       
    WORD $0xd001;  // add       %edx   %eax       
    BYTE $0x5d;    // pop       %rbp   
    BYTE $0xc3;    // retq             
